### ISSUE TITLE
Template links missing pathPrefix if they don't end with '/'

### ISSUE THREAD

**Issue by Caellian** [11ty/eleventy-dev-server#75] opened 2024-03-12 13:38 UTC
I have my nav in `_include` dir. I can access all pages fine, but links in njk template aren't prefixed correctly.

The same links are properly prefixed in files generated with the build command.

This makes it very annoying to use the dev server because I have to manually type in links from templates in `_include` as it behaves differently than the build.

For reference, here's my [config](https://github.com/Caellian/MMS_Infty/blob/e0c2c478c6ac7de4704cb5e9827999d4b0afdb24/eleventy.config.js).

**Comment by Caellian** [comment] 2024-03-12 19:36
Happens only when paths don't end with a forward slash.

I know that dev-server requires paths to end with '/', but this shouldn't affect prefixing as any path that's an absolute path or relative (doesn't specify a different host) should be prefixed.

**Comment by zachleat** [comment] 2024-06-04 16:39
I believe this is a duplicate of #65, shipped with Dev Server v2.0.0.

**Closed by zachleat** 2024-06-04 16:39 UTC
Labels: duplicate
