### ISSUE TITLE
Injected script interferes with the page and breaks it

### ISSUE THREAD

**Issue by pepelsbey** [11ty/eleventy-dev-server#39] opened 2022-07-18 22:47 UTC
## Gist

Shower presentation engine while served with eleventy-dev-server stops working properly after the first reload.

## Steps to reproduce

1. Install the server `npm install -g @11ty/eleventy-dev-server`
2. Clone `git@github.com:shower/shower.git`
3. Install dependencies `npm install`
4. Run the server `eleventy-dev-server`
5. Open http://localhost:8080/
6. Click the first slide
7. Press Right Arrow key a few times to reach the end
8. Press Left Arrow key to go back
9. Open `index.html` in editor and save it
10. Try to navigate the slides, compare the behavior

## Expected behavior

The same, before and after saving the file

## Actual behavior

After the saving slides start to behave weird

---

https://user-images.githubusercontent.com/105274/179629661-3b6b405c-13a5-452c-9b56-78eddb36d30e.mp4

**Comment by zachleat** [comment] 2023-01-26 22:29
I believe this is a duplicate of #7. I _just_ filed what I think will be the follow-up issue there moving forward: https://github.com/11ty/eleventy-dev-server/issues/49

The workaround (for now) is to disable the `domDiff` feature.

**Comment by zachleat** [comment] 2023-01-26 22:29
I’m open to feedback about a breaking change to make `domDiff: false` the default too, hmm.

**Comment by pepelsbey** [comment] 2023-01-26 22:42
Thank you for following up! I think it would be safer to keep the diff disabled by default until you figure out how to make it work. Feel free to close this issue, I'm pretty sure it's a duplicate.

**Comment by zachleat** [comment] 2023-01-26 22:48
Thank you!

**Closed by zachleat** 2023-01-26 22:48 UTC
Labels: duplicate
