### ISSUE TITLE
Server crashing when serving videos

### ISSUE THREAD

**Issue by erikvanek** [11ty/eleventy-dev-server#61] opened 2023-03-23 10:04 UTC
Hey,
I have recently migrated to eleventy 2.0.

I'm experiencing one DX issue that fortunately does not impact the outcome of file transformation. Just reduces the developer experience I have when using eleventy.

My site hosts several `*.mp4` videos that I'm embedding to several `reveal.js` presentations. When I click a link on my site that points to the presentation, console immediately throws 

`(node:37344) UnsupportedWarning: Status message is not supported by HTTP/2 (RFC7540 8.1.2.4)
(Use node --trace-warnings ... to show where the warning was created)
`

When I use `node --trace warnings` I get this

`
(node:38119) UnsupportedWarning: Status message is not supported by HTTP/2 (RFC7540 8.1.2.4)
    at statusMessageWarn (node:internal/http2/compat:118:13)
    at Http2ServerResponse.set statusMessage [as statusMessage] (node:internal/http2/compat:660:5)
    at write (/home/erik/dev/erikvanek.github.io/node_modules/finalhandler/index.js:279:23)
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at listener (/home/erik/dev/erikvanek.github.io/node_modules/on-finished/index.js:170:15)
    at onFinish (/home/erik/dev/erikvanek.github.io/node_modules/on-finished/index.js:101:5)
    at callback (/home/erik/dev/erikvanek.github.io/node_modules/ee-first/index.js:55:10)
    at Http2ServerRequest.onevent (/home/erik/dev/erikvanek.github.io/node_modules/ee-first/index.js:93:5)
    at Http2ServerRequest.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
`

Once that has happened server is no longer running and I have to restart manually again. When I inspect the `Network` tab within my client the requested resource (video) does not even have a response code. It is just a failed request.

Attaching a picture of my running site and failed network requests.
![eleventy-bug](https://user-images.githubusercontent.com/10098945/227169397-af6a66b6-8f04-4b19-a214-fccd0faa59f5.png)

**Comment by zachleat** [comment] 2024-06-04 15:54
I think this is a duplicate of #51, fixed with dev server 2.0

**Closed by zachleat** 2024-06-04 15:54 UTC
